## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [1]:
import numpy as np

In [15]:
z = np.zeros(5)
print(z,z.dtype)
print(z.itemsize)
print(z.shape)

[0. 0. 0. 0. 0.] float64
8
(5,)


In [18]:
o = np.ones((5,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
m = np.arange(1,21).reshape(4,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
print(m * 10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [26]:
a = m[m % 2 == 1]
print(a.reshape(2,5))

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [43]:
j = list()
m = np.arange(1,21)
for i in m:
    if(i%2 == 0):
        j.append(i * -1)
    else:
        j.append(i)
print(j)

[1, -2, 3, -4, 5, -6, 7, -8, 9, -10, 11, -12, 13, -14, 15, -16, 17, -18, 19, -20]


In [46]:
M1 = np.arange(1,17).reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [47]:
M2 = M1.T
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [48]:
M3 = M1 + M2
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [49]:
MT1 = M3.T
print(MT1)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [55]:
print((MT1 == M3).all()) # 1 way, this doesnt work if one the element/elements in the array are empty. it still returns true
print(np.array_equal(MT1,M3)) # 2 way
print(np.array_equiv(MT1,M3)) # 3 way
print(np.allclose(MT1,M3))  # 4 way

True
True
True
True


In [56]:
M4 = M1 - M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [57]:
MT2 = M4.T
print(MT2)

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]


In [60]:
print((MT2 == M4).all())
print((MT2 == -M4).all())
print(np.array_equal(MT2,M4))
print(np.array_equal(MT2,-M4))

False
True
False
True


In [66]:
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)

[[35 16 25 28]
 [26 13 31 14]
 [36 38 27 12]]


In [71]:
xmax = np.amax(R1,axis = 0)
print(xmax)

[36 38 31 28]


In [72]:
xmin = np.amin(R1,axis = 0)
print(xmin)

[26 13 25 12]


In [75]:
R1[:,:3]

array([[35, 16, 25],
       [26, 13, 31],
       [36, 38, 27]])

In [91]:
n = np.sum(R1[:,:3], axis = 0)
R1[:,3] = n
print(R1)

[[35 16 25 97]
 [26 13 31 67]
 [36 38 27 83]]


In [92]:
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)

[[24 39 25 20]
 [20 36 24 21]
 [10 17 16 26]]


In [98]:
j = list()
R1 = np.random.randint(10,40,12)
print(R1)
for i in R1:
    if(i%2 == 0):
        j.append(np.NaN)
    else:
        j.append(i)
print(j)

[31 27 29 19 37 15 28 31 22 14 12 21]
[31, 27, 29, 19, 37, 15, nan, 31, nan, nan, nan, 21]


In [99]:
print(j.count(np.NaN))

4


In [100]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
