## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [6]:
#create a numpy array of 5 zeros.
import numpy as np
a=np.zeros(5)
print(type(a),a.size,a.shape)

<class 'numpy.ndarray'> 5 (5,)


In [9]:
#create a numpy array of ones of shape (5,4)
a=np.ones(20)
k=a.reshape(5,4)
print(k)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#create a matrix of shape 4,5 with numbers from 1-20
a=np.arange(1,21,1)
k=a.reshape(4,5)
print(k)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
#multiply all elements of above array by 10
a=np.arange(1,21,1)
k=a.reshape(4,5)
k *=10
print(k)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [18]:
#print odd elements from array
a=np.arange(1,21,1)
k=list()
for i in a:
    if (i%2==1):
        k.append(i)
print(k)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [20]:
#replace all even elements by their negative
a=np.arange(1,21,1)
k=list()
for i in a:
    if (i%2==1):
        k.append(i)
    else:
        k.append(i*-1)
print(k)

[1, -2, 3, -4, 5, -6, 7, -8, 9, -10, 11, -12, 13, -14, 15, -16, 17, -18, 19, -20]


In [23]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
a=np.arange(1,17,1)
M1=a.reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [24]:
#create a transpose of above matrix call it M2
M2=M1.transpose()
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [26]:
#find sum of above matrix M3 = (M1 + M2)
M3 = (M1 + M2)
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [27]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1=M3.transpose()
print(MT1)
#Yes, MT1 and M3 are equal

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [28]:
#find diffrence of M4 = (M1 - M2)
M4 = (M1 - M2)
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [30]:
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2=M4.transpose()
print(MT2)
#M4=-MT2

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]


In [69]:
#create a matrix (3x4) R1 of random numbers between 10-40
R=np.random.randint(10,40,12)
R1=R.reshape(3,4)
print(R1)

[[32 19 21 16]
 [20 39 39 22]
 [16 10 15 23]]


In [48]:
#find min and max column wise
print(np.min(R1,axis=1))
print(np.min(R1,axis=0))
print(np.max(R1,axis=1))
print(np.max(R1,axis=0))

[10 18 10]
[10 18 10 15]
[37 38 26]
[38 37 35 18]


In [70]:
#replace the last column with sum of all the columns
s=np.sum(R1,axis=1)
R1[:,-1]=s
print(R1)

[[ 32  19  21  88]
 [ 20  39  39 120]
 [ 16  10  15  64]]


In [88]:
#create a matrix (3x4) R1 of random numbers between 10-40
#replace all even elements with nan in R1
#count number of nan in R1
R1 = np.random.randint(10,40,12)
#17- replace all even elements with nan in R1
R1.resize(3,4)
print(R1)
x = np.where(R1%2==0,np.nan,R1)
print(x)


[[17 31 30 15]
 [24 33 23 28]
 [26 18 19 23]]
[[17 31  1 15]
 [ 1 33 23  1]
 [ 1  1 19 23]]


In [80]:
#check output of this code
a1 = np.arange(1,10).reshape(3,3)
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
