In [1]:
import numpy as np

In [5]:
a = np.array([1,2])
print(a)
print(dir(a))

[1 2]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rl

In [10]:
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
3


In [15]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(type(a))
print(a.size)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
9
(3, 3)
2
4
int32


In [19]:
x = np.zeros(5)
print(x)
print('Data Type : ',x.dtype)
print('Item Size : ',x.itemsize)
print('Shape : ',x.shape)

[0. 0. 0. 0. 0.]
Data Type :  float64
Item Size :  8
Shape :  (5,)


In [27]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
z = np.array(range(1,21)).reshape(4,5)
print(z)
z = np.array(range(1,21)).reshape(4,5)*10
print(z)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [77]:
z = np.array(range(1,21)).reshape(4,5)
print(z)
size = z.shape
r = size[0]
c = size[1]
# printing odd numbers 
for i in range(r) : 
    for j in range(c) :
        if z[i][j] %2 != 0 :
            print(z[i][j])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
1
3
5
7
9
11
13
15
17
19


In [78]:
z = np.array(range(1,21)).reshape(4,5)
print(z)
size = z.shape
r = size[0]
c = size[1]
# replacing even numbers by negitive
for i in range(r) : 
    for j in range(c) :
        if z[i][j] %2 == 0 :
            z[i][j] = -z[i][j]
print(z)
            

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [121]:
m1 = np.linspace(1,16,16).reshape(4,4)
print('--------m1--------')
print(m1)
print()
print('--------m2--------')
m2 = m1.transpose()
print(m2)
print()
print('--------m3--------')
# sum of m1 and m2
m3 = m1 + m2
print(m3)
print()
mt1 = m3.transpose()
print('--------mt1--------')
print(mt1)

size = mt1.shape
r = size[0]
c = size[1]
# replacing even numbers by negitive
for i in range(r) : 
    for j in range(c) :
        if m3[i][j] == mt1[i][j] :
            c = 1

if c == 1 :
    print()
    print('------equal-------')
    
    
# difference between m1 and m2

m4 = m1 - m2
print()
print('---------m4--------')
print(m4)

mt2 = m4.transpose()
print('----------mt2---------')
print(mt2)



--------m1--------
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

--------m2--------
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

--------m3--------
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

--------mt1--------
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

------equal-------

---------m4--------
[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]
----------mt2---------
[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]


In [156]:
r1 = np.array(np.random.randint(10,40,12)).reshape(3,4)
print(r1)

[[11 16 37 31]
 [36 39 18 21]
 [35 16 11 37]]


In [157]:
print()
print('Columns')
print( r1[:,0].max())
print()
print( r1[:,1].max())
print()
print( r1[:,2].max())
print()
print( r1[:,3].max())
print()
print(r1)
print()

for i in range(3) :
    r1[:,3][i] = r1[:,0][i] + r1[:,1][i] + r1[:,2][i]
print(r1[:,3])    


Columns
36

39

37

37

[[11 16 37 31]
 [36 39 18 21]
 [35 16 11 37]]

[64 93 62]
